#!/usr/bin/env python
#
# Copyright 2016 by Chris Osborn <fozztexx@fozztexx.com>
#
# Converts LASM 8080 assembly into Z80 assembly compatible with AS
# macroassembler at http://john.ccac.rwth-aachen.de:8000/as/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.

import argparse
import re
import os
import sys
import tempfile
import shutil

ASSEMBLER = "asl -L -cpu "
P2HEX = "p2hex -F Intel"
PLIST = "plist"
INSTR8080 = {"ACI":"adc", "ADC":None, "ADD":None, "ADI":"add", "ANA":"and", "ANI":"and",
             "CALL":None, "CC":"call", "CM":"call", "CMA":"cpl", "CMC":"ccf", "CMP":"cp",
             "CNC":"call", "CNZ":"call", "CP":"call", "CPE":"call", "CPI":"cp", "CPO":"call",
             "CZ":"call", "DAA":None, "DAD":"add", "DCR":"dec", "DCX":"dec", "DI":None,
             "EI":None, "HLT":"halt", "IN":None, "INR":"inc", "INX":"inc", "JC":"jp",
             "JM":"jp", "JMP":"jp", "JNC":"jp", "JNZ":"jp", "JP":None, "JPE":"jp", "JPO":"jp",
             "JZ":"jp", "LDA":"ld", "LDAX":"ld", "LHLD":"ld", "LXI":"ld", "MOV":"ld",
             "MVI":"ld" ,"NOP":None, "ORA":"or", "ORI":"or", "OUT":None, "PCHL":"jp",
             "POP":None, "PUSH":None, "RAL":"rla", "RAR":"rra", "RC":"ret", "RET":None,
             "RLC":"rlca", "RM":"ret", "RNC":"ret", "RNZ":"ret", "RP":"ret", "RPE":"ret",
             "RPO":"ret", "RRC":"rrca", "RST":None, "RZ":"ret", "SBB":"sbc", "SBI":"sbc",
             "SHLD":"ld", "SPHL":"ld", "STA":"ld", "STAX":"ld", "STC":"scf", "SUB":None,
             "SUI":"sub", "XCHG":"ex", "XRA":"xor", "XRI":"xor", "XTHL":"ex",
             # Directives that also need cleaning
             "DB":None, "DW":None}
TASM = {".EQU":"equ", ".CSEG":";.cseg", ".DSEG":";.dseg", ".ORG":"org", ".TEXT":"db",
        ".DB":"db", ".DW":"dw", ".BLOCK":"ds", ".END":"end"}
INSTRREGEX = ""

processed = []

parser = argparse.ArgumentParser()
parser.add_argument("filename", help="file to assemble")
parser.add_argument("--output", help="file to output")
parser.add_argument("--cpu", default="z80", help="CPU type: 8080 or Z80 (default)")
parser.add_argument("--listing", action="store_true", help="Produce assembler listing in .lst")
parser.add_argument("--tasm", action="store_true", help="Use TASM compatible mnemonics")
args = parser.parse_args()

def fixBoolean(param):
  if re.search("\\b(OR|AND|NOT)\\b", param, flags=re.IGNORECASE):
    param = re.sub("\\bOR\\b", "||", param, flags=re.IGNORECASE)
    param = re.sub("\\bAND\\b", "&&", param, flags=re.IGNORECASE)
    param = re.sub("\\bNOT\\b", "~~", param, flags=re.IGNORECASE)
  return param

def replaceOperators(param):
  if re.search("\\b(OR|AND|NOT|MOD|SHR)\\b", param, flags=re.IGNORECASE):
    param = re.sub("\\bOR\\b", "|", param, flags=re.IGNORECASE)
    param = re.sub("\\bAND\\b", "&", param, flags=re.IGNORECASE)
    param = re.sub("\\bNOT\\b", "~", param, flags=re.IGNORECASE)
    param = re.sub("\\bMOD\\b", "#", param, flags=re.IGNORECASE)
    param = re.sub("\\bSHR\\b", ">>", param, flags=re.IGNORECASE)
  if args.tasm and re.search("%", param, flags=re.IGNORECASE):
    param = re.sub("%", "#", param, flags=re.IGNORECASE)
  return param
  
def fixOperators(param):
  istr = False
  plen = len(param)
  last = 0
  i = 0
  newp = ""
  while i < plen:
    c = param[i]
    if (not istr and c == '"' or c == '\'') or (istr and c == istr):
      if not istr:
        istr = c
      else:
        istr = False
      if istr:
        if i - last:
          newp += replaceOperators(param[last:i])
      elif i - last:
        newp += param[last:i]
      last = i
    i += 1
  if i - last:
    newp += replaceOperators(param[last:i])
  if param != newp:
    sys.stderr.write("NEWP " + newp + "\n")
    sys.stderr.write("OLDP " + param + "\n")
  return newp
  
def fixRegisters(param):
  pcopy = param.split(",")
  regs = param.upper().split(",")

  regs[0] = regs[0].strip()
  if regs[0] == "M":
    pcopy[0] = "(hl)"
  if len(regs) > 1:
    regs[1] = regs[1].strip()
    if regs[1] == "M":
      pcopy[1] = "(hl)"
  return ",".join(pcopy)

def fixStrings(param):
  pcopy = list(param)
  istr = False
  plen = len(pcopy)
  i = 0
  sb = -1
  se = -1
  while i < plen:
    c = pcopy[i]
    if c == '\'':
      if not istr:
        sb = i
      else:
        if i + 1 < plen and pcopy[i+1] == '\'':
          pcopy[i] = '\\'
          istr = not istr
          i += 1
        else:
          se = i
          if se - sb > 2:
            pcopy[sb] = '"'
            pcopy[se] = '"'
      istr = not istr
    elif istr:
      if c == '"':
        pcopy[i] = "\\i"
      elif c == '\\':
        pcopy[i] = "\\\\"
    i += 1
  return "".join(pcopy)

# FIXME - how does LASM put a single quote into a string?
def paramEnd(param):
  istr = False
  plen = len(param)
  i = 0
  while i < plen:
    c = param[i]
    if c == '\'':
      istr = not istr
    if not istr and c == ';':
      break
    i += 1
  return param[:i].rstrip()

def findNth(haystack, needle, n):
  start = haystack.find(needle)
  while start >= 0 and n > 1:
    start = haystack.find(needle, start+len(needle))
    n -= 1
  return start

def convertSyntax(filename):
  lines = []
  lcount = 0
#  ifcount = 0
  ZEOF = False
  path, sname = os.path.split(filename)
  orig, ext = os.path.splitext(sname)
  outfile = os.path.join(tmpdir, orig + ext)

  if filename in processed:
    return outfile
  
  with open(filename) as f:
    for line in f:
      lcount += 1
      line = line.rstrip()
      zpos = line.find('\032')
      if zpos >= 0:
        ZEOF = True
        line = line[:zpos]
        
      m = re.search("^([A-Z0-9_]+)[ \t]+(EQU|SET)[ \t]+([^;]+)", line, flags=re.IGNORECASE)
      if m:
        label = m.group(1)
        mnem = m.group(2).upper()
        param = fixBoolean(m.group(3))
        if label == "FALSE" or label == "TRUE":
          label = ";" + label

        if mnem == "SET":
          mnem = ":="

        param = fixStrings(param)
        line = label + m.string[m.end(1):m.start(2)] \
            + mnem + m.string[m.end(2):m.start(3)] \
            + param + m.string[m.end(3):]

      m = re.search("^[ \t]*(IF)[ \t]+([^;]+)", line, flags=re.IGNORECASE)
      if m:
        mnem = m.group(1)
        param = fixBoolean(m.group(2))
        line = "\t" + mnem + m.string[m.end(1):m.start(2)] \
            + param + m.string[m.end(2):]
        #ifcount += 1
        
      m = re.search("^[ \t]*(ENDIF)([ \t;].*)?$", line, flags=re.IGNORECASE)
      if m:
        line = "\t" + m.string[m.start(1):]
        #ifcount -= 1

      # m = re.search("^[ \t]*(END)\\b", line, flags=re.IGNORECASE)
      # if m:
      #   if ifcount:
      #     lines.append(";##### BAD END " + orig + " " + str(lcount))
      #     #line = ";" + line
        
      m = re.search("^[ \t]*(LINK|INCLUDE)[ \t]+([^ \t;]+)", line, flags=re.IGNORECASE)
      if m:
        mnem = m.group(1).upper()
        incfile = m.group(2).lower()
        incl, iext = os.path.splitext(incfile)
        incl = os.path.join(path, incl)
        
        if not iext:
          iext = ext
        converted = convertSyntax(incl + iext)

        line = "\tinclude\t" + converted
#        if mnem == "LINK":
#          lines.append(line)
#          line = "\tEND"

      # FIXME - deal with RST isntruction. Numbers are different on
      # 8080 vs Z80, and numbers could be macros
      m = re.search("^([A-Z0-9_]+)[ \t]+([A-Z0-9]+)", line, flags=re.IGNORECASE)
      if m:
        label = m.group(1).upper()
        mnem = m.group(2).upper()
        if mnem != "EQU" and mnem != "DB" and mnem != "DW" and label in INSTR8080:
          line = "\t" + line

      m = re.search("^([A-Z0-9_]+:?)?[ \t]*\\b(" + INSTRREGEX + ")\\b[ \t]*(.*)",
                    line, flags=re.IGNORECASE)
      if not m and args.tasm:
        m = re.search("^([A-Z0-9_]+:?)?[ \t]*(" + TASMREGEX + ")\\b[ \t]*(.*)",
                      line, flags=re.IGNORECASE)        
      if m:
        label = m.group(1)
        mnem = m.group(2).upper()
        param = m.group(3).rstrip()
        param = paramEnd(param)
        if label:
          llen = len(label)
          if label[-1] != ':':
            label += ':'
        else:
          label = ""
          llen = 0
        lbeg = label + m.string[llen:m.start(2)]
        lend = m.string[m.start(3) + len(param):]
        param = fixOperators(param)

        omnem = mnem
        new = None
        if args.tasm and mnem in TASM:
          new = TASM[mnem]
        elif mnem in INSTR8080:
          new = INSTR8080[mnem]
        if new:
          mnem = new

        if args.cpu != "8080":
          if omnem == "JNZ":
            param = "nz," + param
          elif omnem == "JZ":
            param = "z," + param
          elif omnem == "JNC":
            param = "nc," + param
          elif omnem == "JC":
            param = "c," + param
          elif omnem == "JPO":
            param = "po," + param
          elif omnem == "JPE":
            param = "pe," + param
          elif omnem == "JP":
            param = "p," + param
          elif omnem == "JM":
            param = "m," + param
          elif omnem == "PCHL":
            param = "(hl)"
          elif omnem == "MVI" or omnem == "MOV":
            param = fixRegisters(param)
            if param[1] == ',' and param[2] == '(' and param[-1] == ')' \
                  and param[2:].upper() != "(HL)":
              param = param[:2] + param[3:-1]
          elif omnem == "ADD" or omnem == "ADC" or omnem == "SUB" or omnem == "SBB":
            param = "a," + fixRegisters(param)
          elif omnem == "ADI" or omnem == "ACI" or omnem == "SUI" or omnem == "SBI" \
                or omnem == "ORI" or omnem == "ANI" or omnem == "XRI" or omnem == "CPI":
            if re.match("^\(.+\)$", param):
              param = param[1:-1]
            param = "a," + param
          elif omnem == "INR" or omnem == "DCR" or omnem == "ORA" or omnem == "ANA" \
                or omnem == "XRA" or omnem == "CMP":
            param = fixRegisters(param)
          elif omnem == "INX" or omnem == "DCX" or omnem == "DAD" or omnem == "LXI":
            reg = param[0].upper()
            if reg == "B":
              reg = "bc"
            elif reg == "D":
              reg = "de"
            elif reg == "H":
              reg = "hl"
            if omnem == "DAD":
              param = "hl," + reg + param[1:]
            else:
              param = reg + param[1:]
            if omnem == "LXI":
              if param[2] == ',' and param[3] == '(' and param[-1] == ')':
                param = param[:3] + param[4:-1]
              if len(param) == 7 and param[2] == ',' \
                    and param[3] == '\'' and param[6] == '\'':
                param = param[:4] + param[5] + param[4] + param[6:]
          elif omnem == "STA" or omnem == "OUT":
            param = "(" + param + "),a"
          elif omnem == "STAX":
            param = param.upper()
            if param == "B":
              param = "(bc),a"
            elif param == "D":
              param = "(de),a"
          elif omnem == "SHLD":
            param = "(" + param + "),hl"
          elif omnem == "LHLD":
            param = "hl,(" + param + ")"
          elif omnem == "SPHL":
            param = "sp,hl"
          elif omnem == "PUSH" or omnem == "POP":
            reg = param.upper()
            if reg == "B":
              param = "bc"
            elif reg == "D":
              param = "de"
            elif reg == "H":
              param = "hl"
            elif reg == "PSW":
              param = "af"
          elif omnem == "LDA" or omnem == "IN":
            param = "a,(" + param + ")"
          elif omnem == "LDAX":
            reg = param.upper()
            if reg == "B":
              param = "a,(bc)"
            elif reg == "D":
              param = "a,(de)"
          elif omnem == "RNZ":
            param = "nz"
          elif omnem == "RZ":
            param = "z"
          elif omnem == "RNC":
            param = "nc"
          elif omnem == "RC":
            param = "c"
          elif omnem == "RPO":
            param = "po"
          elif omnem == "RPE":
            param = "pe"
          elif omnem == "RP":
            param = "p"
          elif omnem == "RM":
            param = "m"
          elif omnem == "CNZ":
            param = "nz," + param
          elif omnem == "CZ":
            param = "z," + param
          elif omnem == "CNC":
            param = "nc," + param
          elif omnem == "CC":
            param = "c," + param
          elif omnem == "CPO":
            param = "po," + param
          elif omnem == "CPE":
            param = "pe," + param
          elif omnem == "CP":
            param = "p," + param
          elif omnem == "CM":
            param = "m," + param
          elif omnem == "XCHG":
            param = "de,hl"
          elif omnem == "XTHL":
            param = "(sp),hl"

        param = fixStrings(param)
        # m = re.search("'.*\\\\.*'", param)
        # if not m:
        #   m = re.search("\".*\\\\.*\"", param)
        # if m:
        #   param = param.replace("\\", "\\\\")

        # Need to create a second line if there's more than 20 arguments
        if (mnem == "DB" or mnem == "DW") and param.count(",") > 19:
          bpos = findNth(param, ",", 20)
          param2 = param[bpos + 1:]
          param = param[:bpos]
          line = lbeg + mnem + "\t" + param + lend
          lines.append(line)
          lbeg = "\t"
          param = param2
          lend = ""
          
        line = lbeg + mnem + "\t" + param + lend
        if line[-1] == '\\':
          line += " "
        
      m = re.search("^(.printx)", line, flags=re.IGNORECASE)
      if m:
        line = "\tmessage \"" + m.string[m.end(1):] + "\""
#      m = re.search("^[ \t]*(title)", line, flags=re.IGNORECASE)
#      if m:
#        line = "\tmessage \"" + m.string[m.end(1):] + "\""

      lines.append(line)
      if ZEOF:
        break

  outfile = os.path.join(tmpdir, orig + ext)
  f = open(outfile, "w")
  for line in lines:
    f.write(line)
    f.write("\n")

  processed.append(filename)
  
  return outfile

INSTRREGEX = ""
for instr in INSTR8080:
  if len(INSTRREGEX):
    INSTRREGEX += "|"
  INSTRREGEX += instr
if args.tasm:
  TASMREGEX = ""
  for instr in TASM:
    if len(TASMREGEX):
      TASMREGEX += "|"
    TASMREGEX += instr
  
if not os.path.exists(args.filename):
  print args.filename + " does not exist"
else:
  tmpdir = tempfile.mkdtemp()
  outfile = convertSyntax(args.filename)

  cmd = ASSEMBLER + args.cpu + " " + outfile
  print cmd
  result = os.system(cmd)
  if (result & 0xff):
    result = result >> 8
  
  path, ext = os.path.splitext(outfile)
  opath, ext = os.path.splitext(args.filename)

  if os.path.exists(path + ".p"):
    cmd = P2HEX + " " + path + ".p " + opath + ".hex" + " -r 0x-0x"
    print cmd
    os.system(cmd)

  if args.listing and os.path.exists(path + ".lst"):
    print "Copying listing output"
    shutil.copy2(path + ".lst", opath + ".lst")
      
  shutil.rmtree(tmpdir)
  sys.exit(result)
